Magento 2139 fav list content is synced to
shopgate/ext-magento-favorites pull request #8
Opened 2018-11-09 07:15 UTC by awesselburg

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2018-11-09 08:19 UTC, augsteyer requested changes
also, the name of the test file is off

2018-11-09 08:19 UTC, augsteyer commented on CHANGELOG.md
> +- synchronize local favorites to Magento after login / registration
```suggestion
- synchronization of guest favorite / wishlist products with Magento after login / registration 
```

2018-11-09 08:19 UTC, augsteyer commented on pipelines/shopgate.user.mergeFavorites.v1.json
> +            {"key": "localProductsIds", "id": "40"}
```suggestion
            {"key": "guestProductIds", "id": "40"}
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: [{ id: 20 }]
```suggestion
      guestProductIds: [{ id: 20 }]
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: [{ id: 20 }]
```suggestion
      guestProductIds: [{ id: 20 }]
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: []
```suggestion
      guestProductIds: []
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: [{ id: 20 }, { id: 30 }]
```suggestion
      guestProductIds: [{ id: 20 }, { id: 30 }]
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: [{ id: 20 }, { id: 30 }]
```suggestion
      guestProductIds: [{ id: 20 }, { id: 30 }]
```

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +      localProductsIds: []
```suggestion
      guestProductIds: []
```

2018-11-09 08:19 UTC, augsteyer commented on extension/lib/magento/customer/getSyncItems.js
> +  const { mageProductsIds, localProductsIds } = input
```suggestion
  const { mageProductsIds, guestProductIds } = input
```

2018-11-09 08:19 UTC, augsteyer commented on extension/lib/magento/customer/getSyncItems.js
> +    addProductsIds: _.differenceWith(localProductsIds, mageProductsIds, _.isEqual),
```suggestion
    addProductsIds: _.differenceWith(guestProductIds, mageProductsIds, _.isEqual),
```

2018-11-09 08:19 UTC, augsteyer commented on extension/lib/magento/customer/getSyncItems.js
> +    productIds: _.concat(mageProductsIds, localProductsIds)
```suggestion
    productIds: _.concat(mageProductsIds, guestProductIds)
```

2018-11-09 08:19 UTC, augsteyer commented on extension/lib/magento/customer/getSyncItems.js
> + * @param {Object[]} input.localProductsIds
```suggestion
 * @param {Object[]} input.guestProductIds
```

2018-11-09 08:19 UTC, augsteyer commented on pipelines/shopgate.user.mergeFavorites.v1.json
> +}
newline

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +  it('Should return correct arrays current products ids - no mage products', async () => {
wait a second, don't you already have this test above? I mean, I know it compares different things, but you are allowed to have more than 1 assert within one test.

2018-11-09 08:19 UTC, augsteyer commented on pipelines/shopgate.user.getCustomerFavorites.v1.json
>      "public": true
can you move `public` above `input`. I think it's a better arrangement for readability. I do believe output should be at the bottom though, unlike the way we had been doing.

2018-11-09 08:19 UTC, augsteyer commented on pipelines/shopgate.user.getCustomerFavorites.v1.json
> +          {"key": "mageProducts", "id": "120"}
maybe this also can be `mageProductIds`?

2018-11-09 08:19 UTC, augsteyer commented on pipelines/shopgate.user.mergeFavorites.v1.json
> +    "output": [
can u move this key below steps (at the end)

2018-11-09 08:19 UTC, augsteyer commented on extension/test/newman/collection.json
> +			"name": "Sync",
the test structure is off, I mean, we have "guest", "customer" and "sync". I feel like something went horribly wrong with this structure ^_^ @andre-kraus , can you help? In the last fav review my suggestion was to break it down into: 
```
-> get/add/delete
-> update
-> sync
```
I think it is better, no?

2018-11-09 08:19 UTC, augsteyer commented on extension/test/unit/lib/magento/customer/syncItems-test.js
> +  it('Should return correct arrays current products ids - no local products', async () => {
`Should return correct arrays current products ids` in all tests is a bit confusing. Are you trying to say `Should not return guest product ids`?

2018-11-19 07:17 UTC, andre-kraus requested changes

2018-11-19 07:17 UTC, andre-kraus commented on pipelines/shopgate.user.mergeFavorites.v1.json
> +    "output": [
Wouldn't recommend that. If it's a pipeline with a lot of steps, you need to always scroll down to the what the pipeline is going to return. So signature should be easily visible (input, output on top).

2018-11-19 14:31 UTC, augsteyer commented
Alright, my environment still is not in good shape so I cannot test the app function or test running.
@andre-kraus can you check the newman tests and run the following app scenario:
1) login as user X
2) add item to favorites
3) logout
4) add items to favorites
5) login as user X
Check items merged

2018-11-19 14:36 UTC, andre-kraus requested changes

2018-11-19 14:36 UTC, andre-kraus commented on extension/test/unit/lib/magento/customer/getSyncItems-test.js
> +  it('Should return the full list of products ids and correct array of product id(s) to add by adding one guest product', async () => {
Should be product ids not products ids

2018-11-19 14:36 UTC, andre-kraus commented on extension/test/unit/lib/magento/customer/getSyncItems-test.js
> +  it('Should return the full list of products ids and a empty array of products id(s) to add because the product products are the same', async () => {
Same as above, please fix all occurrences.

2018-11-19 15:05 UTC, andre-kraus commented
> Alright, my environment still is not in good shape so I cannot test the app function or test running.
> @andre-kraus can you check the newman tests and run the following app scenario:
> 
> 1. login as user X
> 2. add item to favorites
> 3. logout
> 4. add items to favorites
> 5. login as user X
>    Check items merged

Working

2018-11-19 15:05 UTC, andre-kraus approved these changes

2018-11-19 15:07 UTC, augsteyer approved these changes

2018-11-19 15:17 UTC, merged