MAGENTO-2306 refactoring wishlist ID getter + storage item removal
shopgate/ext-magento-favorites pull request #9
Opened 2019-01-09 12:51 UTC by augsteyer

## Description

Performance update for wishlist ID getting. Added removal of wishlist products for future performance gains. No change log as the initial version is not released.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2019-01-09 14:05 UTC, Skistims requested changes

2019-01-09 14:05 UTC, Skistims commented on extension/lib/magento/customer/deleteItems.js
> +    return deleteItemsFromStorage()
if the wishlistItemIdsString is empty, it means the productIds were not found in the mapping from the storage. This call seems unnecessary

2019-01-09 14:05 UTC, Skistims commented on extension/lib/magento/customer/deleteItems.js
> +  await deleteItemsFromStorage()
definitely no need to await this.

2019-01-09 14:05 UTC, Skistims commented on extension/lib/magento/customer/deleteItems.js
> +  await request.send(wishlistItemsEndpointUrl, 'deleteFavorites', 'DELETE')
probably no need to await this.
As we do not need reponse (it is empty anyway) and the errorhandling is happening within the send function.
So waiting for the API here causes unnecessary delay

2019-01-09 14:05 UTC, Skistims commented on extension/lib/magento/customer/deleteItems.js
> +      context.storage.user.map.delItem('wishlistItemIdMapping', id)
for the record:
If you want to keep the item mapping clean all the time (no dead entries) that is okay, even though I don't see any upside.
Just wanted to let you know, that the mapping is reinitiated every time the getFavorites pipeline is called. This is also implied, when the putFavorites pipeline is called, which happens pretty often.
So maybe this changes your mind about cleaning this up at all.

2019-01-10 03:00 UTC, augsteyer commented on extension/lib/magento/customer/deleteItems.js
> +  await request.send(wishlistItemsEndpointUrl, 'deleteFavorites', 'DELETE')
will have to confirm on how contained the `steps` are, aka can 2 steps be getting called at the same time

2019-01-10 03:04 UTC, augsteyer commented on extension/lib/magento/customer/deleteItems.js
> +      context.storage.user.map.delItem('wishlistItemIdMapping', id)
yup, did not notice that due to how inconsistently the storage clearing worked, see the **possible** fix. I say possible as it is hard to be a 100% with async bugs due to inconsistent results with different server loads/runs.

2019-01-10 09:17 UTC, Skistims approved these changes

2019-01-10 09:23 UTC, augsteyer commented on extension/lib/magento/customer/deleteItems.js
> +  await request.send(wishlistItemsEndpointUrl, 'deleteFavorites', 'DELETE')
Waldemar confirmed that there can be issues between steps and async calls. We do not want to create a race condition between the delete endpoint call and the get wishlist item call. So if for some reason magento hiccups and delete takes longer than the getItems, then the getItems call will think that there are more products than there actually are.

2019-01-10 09:27 UTC, merged